config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :attempts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :game
  delegate :word, :attempts, :attempt_limit, to: :game

  attribute(
    :letters,
    Type::Custom.new(
      wraps: ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array.new(
        ActiveRecord::Type::String.new
      ),
      in: {
        String => ->(value) { value.each_char.with_index.map { |char, index| Letter.new(value: char.presence, index: index) } },
        Array => ->(value) { value.each_with_index.map { |char, index| Letter.new(value: char.presence, index: index) } }
      },
      out: ->(letters) { letters.map(&:value) },
    ),
    default: -> { [] }
  )

  validates_inclusion_of :guess, in: Dictionary.popular
  validates_length_of :attempts, maximum: ->(attempt) { attempt.attempt_limit }

  def correct?
    letters.all?(&:correct?)
  end

  def guess
    letters.map(&:value).join("")
  end

  def letters_attributes
    letters.map(&:attributes)
  end

  def letters_attributes=(value)
    self.letters = case value
    when Hash
      value.sort_by(&:first).map { |_, hash| hash[:value] }
    else
      value
    end
  end

  def score!
    letters.zip(word.each_char) do |letter, answer|
      if letter.value == answer
        letter.correct!
      end
    end

    letters.filter(&:unknown?).each do |candidate|
      word.each_char.with_index do |answer, index|
        if candidate.value == answer && !letters.map(&:correct_index).include?(index)
          candidate.present_for!(index: index)
        end
      end
    end

    letters.filter(&:unknown?).each(&:absent!)
  end

  class Letter
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :value, :string
    attribute :score, :string, default: :unknown
    attribute :index, :integer
    attribute :correct_index, :integer

    def value=(value)
      super(value.try { downcase.chomp })
    end

    def correct!
      self.score = :correct
      self.correct_index = index
    end

    def present_for!(index:)
      self.score = :present
      self.correct_index = index
    end

    def absent!
      self.score = :absent
    end

    def unknown?
      score.inquiry.unknown?
    end

    def correct?
      score.inquiry.correct?
    end

    def attributes
      {"value" => value}
    end
  end
end

app/models/dictionary.rb
class Dictionary
  cattr_accessor :dictionary_path, default: Rails.root.join("vendor/github/dolph/dictionary")
  cattr_accessor :words, default: {
    popular_of_length: {}
  }.with_indifferent_access

  class << self
    def popular
      words[:popular] ||= File.readlines(dictionary_path.join("popular.txt"), chomp: true)
    end

    def popular_of_length(length)
      words[:popular_of_length][length] ||= popular.filter { |word| word.length == length }
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :attempts
  validates_inclusion_of :word, in: Dictionary.popular

  def current_attempt
    attempts.new(
      letters: " " * word.length
    )
  end

  def remaining_attempts
    remaining_attempt_count.times.map {
      attempts.new(letters: " " * word.length)
    }
  end

  def remaining_attempt_count
    [0, attempt_limit - attempts.length].max
  end

  def scored
    score!
    self
  end

  def score!
    attempts.each(&:score!)
  end

  def incomplete?
    status == :incomplete
  end

  def status
    if attempts.last&.correct?
      :won
    elsif remaining_attempt_count == 0
      :lost
    else
      :incomplete
    end
  end

  def self.with_random_word(length: 5)
    create_with(word: Dictionary.popular_of_length(length).sample)
  end
end

app/models/type/custom.rb
module Type
  class Custom < ActiveModel::Type::Value
    def initialize(wraps:, in: {}, out: :itself.to_proc, **args)
      @wrapped_type = wraps
      @in = binding.local_variable_get(:in)
      @out = out

      super(**args)
    end

    def type
      :custom
    end

    def cast_value(value)
      @in.each do |type, transform|
        if value.is_a?(type)
          return transform.call(value)
        end
      end

      value
    end

    def deserialize(value)
      cast_value(@wrapped_type.deserialize(value))
    end

    def serialize(value)
      @wrapped_type.serialize(@out.call(value))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @attempt = @game.attempts.create!(attempt_params)

    redirect_back_or_to @game
  end

  def attempt_params
    params[:attempt].permit(letters_attributes: [:value])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.order(created_at: :desc)
  end

  def show
    @game = Game.find(params[:id]).scored
  end

  def create
    @game = Game.with_random_word(length: length_param).create!(game_params)
    redirect_to @game
  end

  def game_params
    params.fetch(:game, {}).permit(:word, :attempt_limit)
  end

  def global_params
    params.permit(:length)
  end

  def length_param
    global_params.fetch(:length, 5).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Hello Wordsmiths!</h1>

<%= form_with model: Game.new do |form| %>
  <%= form.label :word %>
  <br>
  <%= form.text_field :word %>
  <br>
  <%= form.label :attempt_limit %>
  <br>
  <%= form.number_field :attempt_limit %>
  <br>
  <%= form.submit %>
<% end %>

<%= button_to "Surprise Me", action: :create %>
<%= button_to "Surprise Me (3 letter word)", action: :create, params: { length: 3 } %>

<ol>
  <% @games.each do |game| %>
    <li><%= link_to game.created_at.in_time_zone("Central Time (US & Canada)").to_fs(:short), game %></li>
  <% end %>
</ol>

app/views/games/show.html.erb
<%
def score_to_css(score)
  guess_to_css = {
    correct: "lightgreen",
    present: "lightyellow",
    absent: "revert",
    unknown: "purple"
  }.with_indifferent_access
  guess_to_css.fetch(score) { "red" }
end
%>

<%= link_to "Games", games_path %>

<br>

<% @game.attempts.each do |attempt| %>
  <% attempt.letters.each do |letter| %>
    <input type=text value="<%= letter.value %>" style="background-color: <%= score_to_css(letter.score) %>" autocomplete=nope size=1 maxlength=1 minlength=1 disabled>
  <% end %>
  <br>
<% end %>

<% if @game.incomplete? %>
  <%= form_with model: [@game, @game.current_attempt], data: { controller: "auto-advance"} do |form| %>
    <%= form.fields_for :letters do |letters_fields| %>
      <%= letters_fields.text_field(
        :value,
        autocomplete: "off",
        size: 1,
        maxlength: 1,
        minlength: 1,
        required: true,
        autofocus: letters_fields.object == form.object.letters.first,
        data: { action: "keydown->auto-advance#keydown"}
      ) %>
    <% end %>
    <%= form.submit "Guess" %>
  <% end %>

  <% @game.remaining_attempts.each do |attempt| %>
    <% attempt.letters.each do %>
      <input type=text autocomplete=nope size=1 maxlength=1 minlength=1 disabled>
    <% end %>
    <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordmasterRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://unpkg.com/tinypebblecss@1.0.1/dist/pebble.min.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>